-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."softcartDimDate"
(
    dateid integer,
    day date,
    weekday integer,
    weekdayname character varying(12),
    month integer[],
    monthname character varying(13),
    quarter integer,
    quartername "char",
    PRIMARY KEY (dateid)
);

CREATE TABLE public."softcartDimCategory"
(
    categoryid integer,
    categoryname character varying(12),
    PRIMARY KEY (categoryid)
);

CREATE TABLE public."softcartDimItem"
(
    itemid integer,
    itemname character varying(13),
    categoryid integer,
    price numeric,
    PRIMARY KEY (itemid)
);

CREATE TABLE public."softcartFactSales"
(
    orderid integer,
    dateid integer,
    itemid integer,
    countryid integer,
    PRIMARY KEY (orderid)
);

CREATE TABLE public."softcartDimCountry"
(
    countryid integer,
    countryname character varying(20),
    PRIMARY KEY (countryid)
);

ALTER TABLE public."softcartDimItem"
    ADD FOREIGN KEY (categoryid)
    REFERENCES public."softcartDimCategory" (categoryid)
    NOT VALID;


ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (itemid)
    REFERENCES public."softcartDimItem" (itemid)
    NOT VALID;


ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (countryid)
    REFERENCES public."softcartDimCountry" (countryid)
    NOT VALID;


ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (dateid)
    REFERENCES public."softcartDimDate" (dateid)
    NOT VALID;

END;